### ISSUE TITLE
End Time Selection Truncated

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#111]
Under some circumstance, the end time selection is truncated.

I just saw it today May 1  10:59am. When clicking anywhere above 6pm on the timeline view (for the TTO), I get full start time options but only end time options from 9am-6pm. Even though there are open slots all the way until 8pm. 

![screen shot 2013-05-01 at 10 50 48 am](https://f.cloud.github.com/assets/273653/449339/79f0c6aa-b26f-11e2-8aa7-fb8c53d4db77.png)

I also took a database snapshot just now in case it will help bug hunt this.

**Comment by njlxyaoxinwei** [comment]
Same issue reported in #182 , Closing this
