### ISSUE TITLE
iPad bug - can’t update data objects

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#181]
Clicking on a data object seems to take you to a new page (with navigation bars, image attached). You can select the dropdowns and everything on this page, but you cannot press submit.

![image](https://f.cloud.github.com/assets/273653/1021524/19bc4718-0d0b-11e3-8dab-855f55dc79e6.jpg)

**Comment by njlxyaoxinwei** [comment]
Fixed by using bootstrap, instead of thickbox modals in #273
