### ISSUE TITLE
Can't create recurring shifts

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#212]
When I try to create a recurring shift on shifts.yale.edu/stcdev, I get this error:

>Error: repeating event could not be saved.
>'Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '21:30:00 UTC AND end >= 2014-02-17 19:00:00 UTC) OR (user_id = 4 AND active = tr' at line 1: SELECT `shifts`.* FROM `shifts` WHERE ((user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-02-17 21:30:00 UTC AND end >= 2014-02-17 19:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-02-24 21:30:00 UTC AND end >= 2014-02-24 19:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-03-03 21:30:00 UTC AND end >= 2014-03-03 19:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-03-10 20:30:00 UTC AND end >= 2014-03-10 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-03-17 20:30:00 UTC AND end >= 2014-03-17 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-03-24 20:30:00 UTC AND end >= 2014-03-24 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-03-31 20:30:00 UTC AND end >= 2014-03-31 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-04-07 20:30:00 UTC AND end >= 2014-04-07 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-04-14 20:30:00 UTC AND end >= 2014-04-14 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-04-21 20:30:00 UTC AND end >= 2014-04-21 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-04-28 20:30:00 UTC AND end >= 2014-04-28 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-05-05 20:30:00 UTC AND end >= 2014-05-05 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-05-12 20:30:00 UTC AND end >= 2014-05-12 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-05-19 20:30:00 UTC AND end >= 2014-05-19 18:00:00 UTC) OR (user_id = 4 AND active = true AND department_id = 1 AND start <= 2014-05-26 20:30:00 UTC AND end >= 2014-05-26 18:00:00 UTC))

**Comment by njlxyaoxinwei** [comment]
This is fixed at commit [fe1aa4](https://github.com/YaleSTC/shifts/commit/fe1aa4b5a331538b8817bc69fe3a08d9efd6ab02) and commit [60ebfc](https://github.com/YaleSTC/shifts/commit/60ebfcd96e599cdde4b86b4347a9084bc0ba3bc7)
