### ISSUE TITLE
Shift Reports Not Being Emailed

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#215]
On shifts.yale.edu/stcdev shift reports aren't being emailed (from the Rails 3 branch).

I've tested two ways, neither case received an email.
1. David/Raph had shifts in pNut on Monday while erin.maher@yale.edu was set as the receiving shift reports email, and she never got the shift reports email
2. Just now, Erin signed in / submitted an unscheduled shift in pNut while casey.watts@yale.edu was set as the receiving shift reports email, and he never got the shift reports email.

It's possible it's a deploy issue or a code issue. We can most easily determine whether it works while running locally first, so let's start there.

**Comment by njlxyaoxinwei** [comment]
Emails are still not sent in Shifts. It could be that we need additional script on the deployment side to run the delayed_job start, or it could be something else.

**Comment by njlxyaoxinwei** [comment]
Addressed now in #449

**Comment by njlxyaoxinwei** [comment]
Emails are now sent, closing this
