### ISSUE TITLE
Set up Continuous Integration through Travis CI 

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/shifts#276]
I'm interested in setting up some type of CI (Continuous Integration).  The purpose of CI is to build your project after every commit so that you can tell if something breaks in the code. 
According to https://www.quora.com/GitHub/What-are-some-continuous-integration-services-that-have-built-in-support-for-the-Github-commit-status-API?share=1, here are possible services that integrate with the Github commit API:
~~www.circleci.com~~ (no free plan)
www.codeship.io (free: 1 concurrent build/50 builds per month/5 private projects/unlimited members)
~~www.semaphoreapp.com~~ (no free plan)
~~www.shippable.com~~ (no slack integration)
www.travis-ci.org (free: fair use/unlimited build minutes/unlimited repos/unlimited collaborators)

It seems that CodeShip and Travis-CI are the best choices at first glance. Travis CI seems much more widely used, but its downfall is that it doesn't support private repos. Since we don't really use private repos with STC, I think that Travis CI is the way to go. I'm investigating both, though.

**Comment by njlxyaoxinwei** [comment]
@mnquintana Now that the integration test suite is ready, what do we need to do to set this up?

**Comment by mnquintana** [comment]
@njlxyaoxinwei I just enabled Travis for Shifts – now we have to add and configure a `.travis.yml` file. Since I set it up for Reservations I could do the same for Shifts, or you could look through Travis' documentation and write it yourselves – either way.

**Comment by njlxyaoxinwei** [comment]
@mnquintana Thanks! Jason had previous set up a `.travis.yml` but I will probably need to tweak it around to reflect recent changes in codebase.

**Comment by mnquintana** [comment]
@njlxyaoxinwei Sure, do you want me to open a separate PR for it? Push straight to master? Or push to your branch?

**Comment by njlxyaoxinwei** [comment]
@mnquintana This is something that is done only on Slack. You should follow the instructions [here](http://docs.travis-ci.com/user/notifications/#Slack-notifications) for slack. And once you see the settings to add to yaml, you can message them to me on Slack and I'll add them (probably after encrypting them). I am currently trying to make a working .travis.yml.

**Comment by njlxyaoxinwei** [comment]
Currently 4 tests mysteriously fail on Travis:

```
1) TimeSlot For one-time timeslot when timeslot is created displays the timeslot properly on the time slots page
     Failure/Error: expect_time_slot_to_display_properly(@slot, time_slot_row(@slot.location.id, Date.today).find('li.timeslot'))
       expected "width: 46.875%; left: 0%;" to match /width:\s*81.*%\s*/
       Diff:
       @@ -1,2 +1,2 @@
       -/width:\s*81.*%\s*/
       +"width: 46.875%; left: 0%;"
       
     # ./spec/support/time_slot_helper.rb:23:in `expect_time_slot_to_display_properly'
     # ./spec/features/time_slots_spec.rb:24:in `block (4 levels) in <top (required)>'
                                                                                
  2) TimeSlot For one-time timeslot when timeslot is created displays the timeslot properly on the shifts schedule page
     Failure/Error: expect_time_slot_to_display_properly(@slot, shift_schedule_row(@slot.location.id, Date.today).find('li.bar_open'))
       expected "width:31.25%; left:15.625%" to match /width:\s*81.*%\s*/
       Diff:
       @@ -1,2 +1,2 @@
       -/width:\s*81.*%\s*/
       +"width:31.25%; left:15.625%"
       
     # ./spec/support/time_slot_helper.rb:23:in `expect_time_slot_to_display_properly'
     # ./spec/features/time_slots_spec.rb:30:in `block (4 levels) in <top (required)>'
                                                                                
  3) TimeSlot For repeating time_slots Different types of deletion can delete future timeslots
     Failure/Error: expect(time_slot_row(@slot.location.id, Date.today)).to have_selector('li.timeslot')
       expected to find css "li.timeslot" but there were no matches
     # ./spec/features/time_slots_spec.rb:83:in `block (4 levels) in <top (required)>'
                                                                                
  4) Tooltip Tooltip on TimeSlot page Tooltip for existing timeslots can edit existing timeslot from tooltip
     Failure/Error: expect_time_slot_to_display_properly(@slot, time_slot_row(@slot.location.id, Date.today).first('li.timeslot'))
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/support/time_slot_helper.rb:23:in `expect_time_slot_to_display_properly'
     # ./spec/features/tooltip_spec.rb:88:in `block (4 levels) in <top (required)>'
```

**Comment by njlxyaoxinwei** [comment]
The reason (at least for the first failing test) is probably this puzzling issue with time zone: Somehow the dates in DB are not UTC value but they are interpreted as UTC by rails when it is exacted.

```
#<TimeSlot id: 1, location_id: 1, calendar_id: 1, repeating_event_id: nil, start: "2014-09-01 10:15:00", end: "2014-09-01 16:45:00", active: true, created_at: "2014-09-01 10:05:00", updated_at: "2014-09-01 10:05:00">
Mon, 01 Sep 2014 06:15:00 EDT -04:00 //time_slot.start
Mon, 01 Sep 2014 12:45:00 EDT -04:00 //time_slot.end
```

**Comment by njlxyaoxinwei** [comment]
Confirmed that on TravisCI `Time.now` returns UTC time, thus causing the errors. I will set the system time zone to EST.

**Comment by njlxyaoxinwei** [comment]
@mnquintana I just made the build pass on TravisCI. Now you can just push to branch 276_travis_ci directly when you have time to enable Slack integration!
