### ISSUE TITLE
Error on first-run LDAP config

### ISSUE THREAD

**Issue by mnquintana** [YaleSTC/shifts#309]
If you choose to configure LDAP in the first-run app config, then once you proceed past step 2 (naming your department), the app raises this error:

```
NoMethodError at /firstrun/first_user
undefined method `observe_form' for #<#<Class:0x007fc2be042f30>:0x007fc2c2651120>

app/views/first_run/_form.html.erb L:49
```

@dgoerger and I discovered that the observe_form method was provided by prototype and has been [deprecated since Rails 2.3.8](http://apidock.com/rails/ActionView/Helpers/PrototypeHelper/observe_form)

Apparently the rails_upgrade plugin missed a lot of stuff (and so did we).

**Comment by njlxyaoxinwei** [comment]
Overridden by #350
