### ISSUE TITLE
Shift Stats Email - Bugfixes

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#347]
- [x] 1. All stats in the email currently return as `0`.
- [x] 2. We wanted late/missed/leftearly shifts to have a link to the shift report, but Rails 2 couldn't for some reason. I think it just wasn't aware of the root URL we're on? (see #88 too). In the meantime we put the shift ID number, but really there should just be a link here to the shift's absolute URL.
- [x] 3. `More Stats` link is a relative link which never works - but Rails 3 should be able to do an absolute link like 2.

Recurring emails are sent by the [`whenever`](https://github.com/javan/whenever) gem which creates cron jobs for rake tasks like this one `UserMailer#email_stats?`
- [schedule.rb](https://github.com/YaleSTC/shifts/blob/9e21281c6d9388730dda590a8e36b53d97ef6ad2/config/schedule.rb#L25) schedules the emails
- [email_stats.rake](https://github.com/YaleSTC/shifts/blob/9e21281c6d9388730dda590a8e36b53d97ef6ad2/lib/tasks/email_stats.rake) gathers the data
- [user_mailer.rb](https://github.com/YaleSTC/shifts/blob/9e21281c6d9388730dda590a8e36b53d97ef6ad2/app/mailers/user_mailer.rb#L159) has the template

**Comment by njlxyaoxinwei** [comment]
Addressed now in #449

**Comment by njlxyaoxinwei** [comment]
the start date and end date was passed in the wrong order, thus producing 0
