### ISSUE TITLE
Permissions Issue when creating a new shift

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/shifts#351]
Testing dev version of shifts:

Signed up for a shift under "Testing" location:
Error message: You don't have permission to sign up for a shift there.
Redirects to: http://development.shifts.yale.edu/stcdev/shifts

**Comment by njlxyaoxinwei** [comment]
Permission not set for the role in DB.

**Comment by jasonkliu** [comment]
Is the third point in #435? :seedling:

**Comment by njlxyaoxinwei** [comment]
@jasonkliu Not sure...This was a long time ago, and I don't know what DB Casey used...It probably just has to do with Casey not giving the "Developer" role the permissions in Testing location.
