### ISSUE TITLE
Intermittent 404 on the STC instance of Shifts

### ISSUE THREAD

**Issue by shippy** [YaleSTC/shifts#356]
Sijia Song reported in an e-mail:

> So this screen appears whenever I submit anything, be it taking a sub request, submitting a shift report or submitting a payform.

![image](https://cloud.githubusercontent.com/assets/1340280/4130075/4b26f6bc-3330-11e4-9d6c-121eb2d3c520.png)

It doesn't seem this is a widespread problem on v2.0, but we should investigate nevertheless, just to make sure that whatever is causing this will not persist through v3. In the meantime, I have asked Sijia to attempt to replicate in a different browser.

**Comment by njlxyaoxinwei** [comment]
Another student had some problems visiting the Shifts site using chrome too. It was because something is wrong in the browser's cache or cookies. I will follow up with this student and see if it has the same cause
