### ISSUE TITLE
Setup for integration testing

### ISSUE THREAD

**Issue by shippy** [YaleSTC/shifts#367]
In order to cover wide swathes of code and make sure they don't regress, we need broad strokes first. To that end, we need to:

* [x] [Mock out CAS](https://github.com/rubycas/rubycas-client#testing)
* [x] Install Capybara and make it functional

This is a prerequisite for the rest of Sprint 2 and needs attending ASAP. If problems are encountered, we should bring them up with Dan Franko of ITS QA, who should be able to help.

**Comment by njlxyaoxinwei** [comment]
On the branch [367 integration tests on beta 8](https://github.com/YaleSTC/shifts/tree/367_integration_tests_on_beta8) I have everything set up in the spec directory:
- factories contains factory_girl factories
- features contains integration tests
- support contains helper modules whose inclusion is defined in rails_helper.rb
- rails_helper.rb: includes all helper modules with respective tags. __This file is the only one that needs to be required in each feature spec__
- spec_helper.rb: Rspec configuration, Database Cleaning and Timecop around each example, Capybara configuration
- test_spec.rb: tests the validity of each factory defined in the factories directory
