### ISSUE TITLE
Replace :should syntax in rspec tests

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/shifts#374]
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. 

We can do this with the transpec gem: http://yujinakayama.me/transpec/

(after #281 and the test suite is fixed)

**Comment by njlxyaoxinwei** [comment]
We scratched the old test suite and this is no longer applicable, as I followed the BDD Expectations
