### ISSUE TITLE
Add `rubyracer` and `execjs` to Gemfile

### ISSUE THREAD

**Issue by shippy** [YaleSTC/shifts#411]
David Backeberg from INF Unix Infrastructure cannot open `bundle exec rails console` on edge version of Shifts deployed to `development.shifts.yale.edu/stcdev`, with the following error message:
```
[hudson@vm-rordevweb-04 current]$  bundle exec rails console
/ror_dev/apps/shifts.yale.edu/stcdev/current/vendor/bundle/ruby/2.1.0/gems/execjs-2.2.1/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
from /ror_dev/apps/shifts.yale.edu/stcdev/current/vendor/bundle/ruby/2.1.0/gems/execjs-2.2.1/lib/execjs.rb:5:in `<module:ExecJS>'
```

StackOverflow suggests that adding just rubyracer, or perhaps rubyracer and execjs, to the Gemfile will resolve this issue.

**Comment by njlxyaoxinwei** [comment]
I have checked with Michael Dunlap from INF Unix that the command
```
RAILS_ENV=production bundle exec rails console
```
runs without error on Central Ruby Farm for DevShifts. No further gems needed. Closing the issue
