### ISSUE TITLE
"Reset Feeds" on Calendar Feeds page

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#420]
1. What is this button supposed to do?
2. When I click it, it sends me to `/calendar_feeds/reset` which says "the page you are looking for doesn't exist"

**Comment by njlxyaoxinwei** [comment]
This button resets the hash, so if someone uses Google Calendar to get events from the ical url,  it invalidates the old one.

**Comment by njlxyaoxinwei** [comment]
Fixed by PR #454
