### ISSUE TITLE
Department page navbar link goes to protected route

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/shifts#437]
Steps to replicate:
1. Visit root / home page (`/`)
2. Click on second link on navbar (e.g. 'STC Developers') which links to `/departments/1`
3. Receive superuser / authorization redirection

If it's not meant to be visible to most users then we shouldn't have it on navbar, or we should just have it link to the home page as well.

**Comment by njlxyaoxinwei** [comment]
duplicated #398
