### ISSUE TITLE
Make_future methods for Shifts and TimeSlots fail on some machines

### ISSUE THREAD

**Issue by njlxyaoxinwei** [YaleSTC/shifts#446]
For some reason the SQL generated in these two methods aren't recognized by some mysql on Mac OS X. Maybe this is a version specific thing but these two methods are very poorly written too so we should rewrite these two with Rails ActiveRecord

**Comment by mnquintana** [comment]
Are you sure it's a Mac thing and not a version-specific thing?

**Comment by njlxyaoxinwei** [comment]
@mnquintana Somehow this happened on both Macs that I tried to set up Shifts on. No Linux distros had any problems...

**Comment by mnquintana** [comment]
Hmmm with the same version number?

**Comment by jasonkliu** [comment]
https://github.com/YaleSTC/shifts/blob/fd3c348f8e9e39ae9ffdfb263e371817803365cb/app/models/time_slot.rb#L35

**Comment by njlxyaoxinwei** [comment]
We can use Arel to better generate SQL queries for conflict, and use [ActiveRecordImport gem](https://github.com/zdennis/activerecord-import) to insert TimeSlots records

**Comment by jasonkliu** [comment]
Method to output days by index number:

Input: Start Date (2015-01-12), End Date (2015-02-26), Days of Week array [1, 3, 5]
Note that `Date.commercial(2015, 3, 1)` gives the 3rd week of 2015..

```rb
require 'date'

  def week_dates(start_date, end_date, table )
    # puts start_date
    # puts end_date
    # puts table
    array = Array.new
    (start_date..end_date).each do |i|
       # puts i.wday
       array << i if table.include? i.wday
    end
    puts array
  end

  puts week_dates(Date.commercial(2015, 3, 1), Date.today, [1, 3, 5])
```

**Comment by njlxyaoxinwei** [comment]
The problem occurs on the following version (probably has to do with OS X version):
```
mysql  Ver 14.14 Distrib 5.6.22, for osx10.10 (x86_64) using  EditLine wrapper
```
But the new make_future for time_slots works on the said machine.

**Comment by njlxyaoxinwei** [comment]
It turns out mysql **does** freak out about long conditions. Even though the Arel Table can handle the length. I will still process these cases in batches of 450 then
