### ISSUE TITLE
Issue with installing capybara-webkit 

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/shifts#455]
Trace:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    ~/.rbenv/versions/2.1.2/bin/ruby extconf.rb
Command 'qmake -spec macx-g++ ' not available

Makefile not found

An error occurred while installing capybara-webkit (1.3.1), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.3.1'` succeeds before bundling.
```

OS X 10.9.5 -- qt is now a dependency and should be noted in the README.
Seems to be a ~new~ dependency (c10a4b61daf5973b01e6c65e4852f692d588a8f0)

Solve with:
```sh
$ brew install qt
```

More info: https://github.com/bundler/bundler/issues/1768

**Comment by njlxyaoxinwei** [comment]
This is only needed for testing. Should we break the documentation down to list different dependencies for different groups (i.e. test, development, production)?

**Comment by jasonkliu** [comment]
Possibly (`bundle install` will fail otherwise). Is ImageMagick still a dependency? I don't have it installed and everything seems to still work out. I think it's required for Reservations...

**Comment by njlxyaoxinwei** [comment]
It is a dependency when you try to upload and crop a profile pic

**Comment by njlxyaoxinwei** [comment]
Updated README
