### ISSUE TITLE
Submit Payform on Sunday Trouble

### ISSUE THREAD

**Issue by caseywatts** [YaleSTC/shifts#84]
When a student hasn't worked any shifts in a given week (so they haven't had payform items auto-added), a payform isn't generated for them.

When they try to add training, etc on a the following Sunday, they are generated a payform for the following week, and they submit that.

Maybe the best quick workaround would be to popup a warning if you try to submit a shift on its start date?

**Comment by njlxyaoxinwei** [comment]
Same issue as #441 . Closing this
